### ISSUE TITLE
Webpack build fails with newest loader version

### ISSUE THREAD

**Issue by govorov** [willyelm/pug-html-loader#26]
Hi.
I experience some problems with last loader version:
```
ERROR in ./src/HwrBundle/Resources/assets/templates/stats/item.pug
Module parse failed: /tmp/BotApp/node_modules/pug-html-loader/lib/index.js!/tmp/BotApp/src/HwrBundle/Resources/assets/templates/stats/item.pug Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/tmp/BotApp/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/tmp/BotApp/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/tmp/BotApp/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/tmp/BotApp/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/tmp/BotApp/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/tmp/BotApp/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/tmp/BotApp/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/tmp/BotApp/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/tmp/BotApp/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /tmp/BotApp/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/tmp/BotApp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /tmp/BotApp/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

`1.1.0` works fine.

I suppose the reason is here:
https://github.com/willyelm/pug-html-loader/commit/cca8eb12407bb9297f43750752a9dd6adc844379
Thank you.

**Comment by willyelm** [comment]
Please see #25, in order to transform the template into a string use raw-loader
