### ISSUE TITLE
Module parse failed for all .pug files

### ISSUE THREAD

**Issue by ztzven** [willyelm/pug-html-loader#3]
Hi there,

I am getting the following error for every pug file after updating to v1.0.7. Downgrading to v1.0.5 fixed the issue.

```
ERROR in *.pug
Module parse failed: */node_modules/pug-html-loader/lib/index.js!*.pug Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (*/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (*/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (*/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (*/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (*/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (*/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (*/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (*/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (*/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (*/node_modules/acorn/dist/acorn.js:1771:23)
 @ *.js 25:18-52
```

**Comment by willyelm** [comment]
Try to use the latest version please

**Comment by infrarosso78** [comment]
hi, i'm using version 1.1.4 and still get the same error. Any idea?

**Comment by rdkleine** [comment]
Version 1.1.5 here same error..

**Comment by bahmanyaghoobi** [comment]
I am getting same error at version '2.0.0-rc.3'
