### ISSUE TITLE
move from v1.1.0 to v1.1.1 broken

### ISSUE THREAD

**Issue by yogesum** [willyelm/pug-html-loader#30]
webpack throws error for each pug file with latest version `v1.1.1`:
**Work perfectly if switched to `v1.1.0`**

*__Error Log__*
```js
 @ ./client/app/job/job-list/job-list.component.js 11:16-41./client/app/job/job-applicant/job-applicant.pug
Module parse failed: /home/yogesh/yogesum/hire/node_modules/pug-html-loader/lib/index.js!/home/yogesh/yogesum/hire/client/app/job/job-applicant/job-applicant.pug Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/yogesh/yogesum/hire/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/yogesh/yogesum/hire/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/yogesh/yogesum/hire/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/yogesh/yogesum/hire/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/yogesh/yogesum/hire/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
```

**Comment by willyelm** [comment]
Please see #25, in order to transform the template into a string use raw-loader
