### ISSUE TITLE
unexpected text "* nor" ——/* normalize component */

### ISSUE THREAD

**Issue by wubinsheng2017** [willyelm/pug-html-loader#55]
/* normalize component */

var component = normalizeComponent(
  src_PriceModevue_type_script_lang_js_,
  PriceModevue_type_template_id_5f5fa4f3_scoped_true_render,
  PriceModevue_type_template_id_5f5fa4f3_scoped_true_staticRenderFns,
  false,
  null,
  "5f5fa4f3",
  null
  
)

→

ERROR in ./packages/unit/src/Unit.vue
Module build failed (from ./node_modules/pug-html-loader/lib/index.js):
Error: ******\packages\unit\src\Unit.vue:7:2
    5|
    6|
  > 7| /* normalize component */
--------^
    8| import normalizer from "!../../../node_modules/vue-loader/lib/runtime/componentNormalizer.js"
    9| var component = normalizer(
    10|   script,

unexpected text "* nor"
    at makeError (******\node_modules\pug-lexer\node_modules\pug-error\index.js:32:13)
    at Lexer.error (******\node_modules\pug-lexer\index.js:59:15)
    at Lexer.fail (******\node_modules\pug-lexer\index.js:1445:10)
    at Lexer.advance (******\node_modules\pug-lexer\index.js:1505:15)
    at Lexer.callLexerFunction (******\node_modules\pug-lexer\index.js:1460:23)
    at Lexer.getTokens (******\node_modules\pug-lexer\index.js:1516:12)
    at lex (******\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (******\node_modules\pug\lib\index.js:100:27)
    at Function.loadString [as string] (******\node_modules\pug-load\index.js:44:24)
    at compileBody (******\node_modules\pug\lib\index.js:86:18)
    at Object.exports.compile (******\node_modules\pug\lib\index.js:242:16)
    at Object.module.exports (******\node_modules\pug-html-loader\lib\index.js:30:22)

**Comment by wubinsheng2017** [comment]
sorry~
webpack.config.js
  config.module.rules.push({
    test: /\.vue$/,
    // use: [
    //   'pug-plain-loader',
    //   'storybook-addon-vue-info/loader'
    // ],
    loader: 'storybook-addon-vue-info/loader',
    enforce: 'post'
  })

  config.module.rules.push({
    test: /\.pug$/,
    loader: 'pug-plain-loader'
  })
→
it's ok！
